name: Artifact example
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Creating a text file
      run: echo "this is sample artifact file" > sample.txt

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: first-artifact
        path: sample.txt
  
