name: Labeling the pr approved
on: pull_request
jobs: 
  labelWhenApproved:
    name: label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: abinoda/label-when-approved-action@v1.0.7
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          ADD_LABEL: "approved"
        
