name: Labeling the pr approved
on: pull_request
jobs: 
  labelWhenApproved:
    name: label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ GH_PAT }}
          ADD_LABEL: "approved"
        
