name: reusable workflow

on: 
  workflow_call:
    inputs: 
      input1:
        required: true
        type: string

jobs:
  greet-user-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Saying hello world
        run: echo "I am saying ${{ inputs.input1 }}"
