name: reusable workflow
on: 
  workflow_call:
    inputs: 
      input1:
      required: true
      typre: string

jobs:
  greet-user-job:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3

      - name: saying hello world
        run: echo "I am saying ${{ inputs.input1 }}"
        
