name: Secrets & Variables example
on: 
  workflow_dispatch:
jobs:
  show_secret_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Access and print secret (safely)
        run: echo "My secret is ${{ secrets.MY_SECRET }}"

      - name: Print the Username
        run: |
          echo "Github Username: $GH_USERNAME"
          echo "GitHub PAT: $GH_PAT"
        
